[[deb]]
=== Install Loud ML with Debian Package

The Debian package for Loud ML can be downloaded from our
<<deb-repo,APT repository>>. It can be used to install
Loud ML on Debian Stretch.

All stable versions of Loud ML can be found in our <<deb-repo,APT repository>>

[[deb-key]]
==== Import the Loud ML PGP Key

include::key.asciidoc[]

[source,sh]
-------------------------
wget -qO - http://loudml.s3-website-eu-west-1.amazonaws.com/repo/gpg/GPG-KEY-LOUDML | sudo apt-key add -
-------------------------

==== Install Dependencies

Debian 9 ships with both Python 3 and Python 2 pre-installed.

You can check the version of Python 3 that is installed in the system by typing:

[source,sh]
--------------------------------------------------
python3 -V
--------------------------------------------------

[[deb-repo]]
==== Installing from the APT repository

ifeval::["{release-state}"=="unreleased"]

Version {version} of Loud ML has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

You may need to install the `apt-transport-https` package on Debian before proceeding:

[source,sh]
--------------------------------------------------
sudo apt-get install apt-transport-https
--------------------------------------------------

Save the repository definition to  +/etc/apt/sources.list.d/loudml-{major-version}.list+:

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/ stretch main" | sudo tee -a /etc/apt/sources.list.d/loudml-{major-version}.list
--------------------------------------------------

endif::[]

ifeval::["{release-state}"=="prerelease"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
echo "deb http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/loudml-{major-version}.list
--------------------------------------------------

endif::[]


[NOTE]
==================================================

These instructions do not use `add-apt-repository` for several reasons:

. `add-apt-repository` adds entries to the system `/etc/apt/sources.list` file
  rather than a clean per-repository file in `/etc/apt/sources.list.d`
. `add-apt-repository` is not part of the default install on many distributions
  and requires a number of non-default dependencies.
. Older versions of `add-apt-repository` always add a `deb-src` entry which
  will cause errors because we do not provide a source package. If you have added
  the `deb-src` entry, you will see an error like the following until you delete
  the `deb-src` line:

    Unable to find expected entry 'main/source/Sources' in Release file
    (Wrong sources.list entry or malformed file)

==================================================

You can install the Loud ML Debian package with:

[source,sh]
--------------------------------------------------
sudo apt-get update && sudo apt-get install loudml
--------------------------------------------------

[WARNING]
==================================================
If two entries exist for the same Loud ML repository, you will see an error like this during `apt-get update`:

["literal",subs="attributes,callouts"]

Duplicate sources.list entry http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/packages/{major-version}/apt/ ...`

Examine +/etc/apt/sources.list.d/loudml-{major-version}.list+ for the duplicate entry or locate the duplicate entry amongst the files in `/etc/apt/sources.list.d/` and the `/etc/apt/sources.list` file.
==================================================

endif::[]

include::skip-set-kernel-parameters.asciidoc[]

[[install-deb]]
==== Download and install the Debian package manually

ifeval::["{release-state}"=="unreleased"]

Version {version} of Loud ML has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

The Debian package for Loud ML v{version} can be downloaded from the website and installed as follows:

["source","sh",subs="attributes"]
--------------------------------------------
wget http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/pool/main/l/loudml/loudml_{version}_all.deb
sudo dpkg -i loudml_{version}_all.deb 
--------------------------------------------

endif::[]

include::init-systemd.asciidoc[]

[[deb-running-init]]
==== Running Loud ML with SysV `init`

Use the `update-rc.d` command to configure Loud ML to start automatically
when the system boots up:

[source,sh]
--------------------------------------------------
sudo update-rc.d loudmld defaults 95 10
--------------------------------------------------

Loud ML can be started and stopped using the `service` command:

[source,sh]
--------------------------------------------
sudo -i service loudmld start
sudo -i service loudmld stop
--------------------------------------------

If Loud ML fails to start for any reason, it will print the reason for
failure to STDOUT. Log files can be found in `/var/log/loudml/`.

[[deb-running-systemd]]
include::systemd.asciidoc[]

[[deb-check-running]]
include::check-running.asciidoc[]

[[deb-configuring]]
==== Configuring Loud ML

include::etc-loudml.asciidoc[]

The Debian package also has a system configuration file (`/etc/default/loudml`),
which allows you to set the following parameters:

include::sysconfig-file.asciidoc[]

NOTE: Distributions that use `systemd` require that system resource limits be
configured via `systemd` rather than via the `/etc/sysconfig/loudml`
file.  See <<systemd>> for more information.

[[deb-layout]]
==== Directory layout of Debian package

The Debian package places config files, logs, and the data directory in the appropriate
locations for a Debian-based system:


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | Loud ML home directory or `$LM_HOME`
  | /usr/share/loudml
 d|

| conf
  | Configuration files including `config.yml`
  | /etc/loudml
  | <<config-files-location,LM_PATH_CONF>>

| conf
  | Environment variables including heap size, file descriptors.
  | /etc/default/loudml
 d|

| data
  | The location of the data files of each model defined
    on the node. 
  | /var/lib/loudml
  | storage.path

| logs
  | Log files location.
  | /var/log/loudml

|=======================================================================

include::next-steps.asciidoc[]
