[[rpm]]
=== Install Loud ML with RPM

The RPM for Loud ML can be <<install-rpm,downloaded the COPR website>>
or from the COPR <<rpm-repo,RPM repository>>. It can be used to install
Loud ML on any RPM-based system such as OpenSuSE, Fedora, SLES, CentOS, Red Hat, and Oracle Enterprise.

NOTE: RPM install is not supported on distributions with old versions of RPM,
such as SLES 11 and CentOS 5.

Stable versions of Loud ML starting from 1.6.0 can be found in the COPR <<rpm-repo,RPM repository>>

[[rpm-copr]]
==== Enable COPR repository

You have two options to do that:

<1> If you’re using a version of Linux with dnf:

[source,sh]
-------------------------
dnf copr enable regel/loudml
-------------------------

You need to have dnf-plugins-core installed.

<2> Or if you have older distribution:

[source,sh]
-------------------------
yum copr enable regel/loudml
-------------------------

You need to have yum-plugin-copr installed.

[[rpm-repo]]
==== Installing from the RPM repository

ifeval::["{release-state}"=="unreleased"]

Version {version} of Loud ML has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

Create a file called `loudml.repo` in the `/etc/yum.repos.d/` directory
for RedHat based distributions, or in the `/etc/zypp/repos.d/` directory for
OpenSuSE based distributions, containing:

ifeval::["{release-state}"=="released"]

["source","sh",subs="attributes,callouts"]
--------------------------------------------------
[copr:copr.fedorainfracloud.org:regel:loudml]
name=Copr repo for loudml owned by regel. Packages for Enterprise Linux 7 - $basearch
baseurl=https://download.copr.fedorainfracloud.org/results/regel/loudml/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/regel/loudml/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
--------------------------------------------------

endif::[]

And your repository is ready for use. You can now install Loud ML with one of the following commands:

[source,sh]
--------------------------------------------------
sudo yum install loudml<1>
sudo dnf install loudml<2>
sudo zypper install loudml<3>
--------------------------------------------------
<1> Use `yum` on CentOS and older Red Hat based distributions
<2> Use `dnf` on Fedora and other newer Red Hat distributions
<3> Use `zypper` on OpenSUSE based distributions

endif::[]

[[install-rpm]]
==== Download and install the RPM manually

ifeval::["{release-state}"=="unreleased"]

Version {version} of Loud ML has not yet been released.

endif::[]

include::skip-set-kernel-parameters.asciidoc[]

include::init-systemd.asciidoc[]

[[rpm-running-init]]
==== Running Loud ML with SysV `init`

Use the `chkconfig` command to configure Loud ML to start automatically
when the system boots up:

[source,sh]
--------------------------------------------------
sudo chkconfig --add loudmld
--------------------------------------------------

Loud ML can be started and stopped using the `service` command:

[source,sh]
--------------------------------------------
sudo -i service loudmld start
sudo -i service loudmld stop
--------------------------------------------

If Loud ML fails to start for any reason, it will print the reason for
failure to STDOUT. Log files can be found in `/var/log/loudml/`.


[[rpm-running-systemd]]
include::systemd.asciidoc[]

[[rpm-check-running]]
include::check-running.asciidoc[]

[[rpm-configuring]]
==== Configuring Loud ML

include::etc-loudml.asciidoc[]

The RPM also has a system configuration file (`/etc/sysconfig/loudml`),
which allows you to set the following parameters:

include::sysconfig-file.asciidoc[]

NOTE: Distributions that use `systemd` require that system resource limits be
configured via `systemd` rather than via the `/etc/sysconfig/loudml`
file.  See <<systemd>> for more information.

[[rpm-layout]]
==== Directory layout of RPM

The RPM places config files, logs, and the data directory in the appropriate
locations for an RPM-based system:


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | Loud ML home directory or `$LM_HOME`
  | /usr/share/loudml
 d|

| conf
  | Configuration files including `config.yml`
  | /etc/loudml
  | <<config-files-location,LM_PATH_CONF>>

| conf
  | Environment variables including heap size, file descriptors.
  | /etc/sysconfig/loudml
 d|

| data
  | The location of the data files of each model defined
    on the node. 
  | /var/lib/loudml
  | storage.path

| logs
  | Log files location.
  | /var/log/loudml

|=======================================================================

include::next-steps.asciidoc[]
