[[release-notes-1.4.3]]
== 1.4.3 Release Notes

The changes listed below have been released for the first time in Loud ML 1.4.3.

[NOTE]
==================================================
Please raise issues on https://github.com/regel/loudml/issues[Github] if you experience compatibility issues on your system.
==================================================

[[community-1.4.2]]
[float]
=== Community

==== Packaging

Added packaging for Ubuntu 18.04.

==== Data sink

Time series prediction can now be saved into a specific data sink:
  - the name of the datasink can be passed to `._predict` endpoint with the parameter `datasink`
  - the name the default data sink can be defined in model settings (`default_datasink`)
  
==== Model description

The `.` character is now allowed in feature fields and measurements.

Two formats are supported to define model features. The first (now deprecated, but still supported):

```
"features": {
    "io": [
       {... feature ...},
       {... feature ...},
       ...
    ],
    "i": [...],
    "o": [...]
}
```

and the second, new, format:

```
"features": [
   {... feature ...},
   {... feature ...},
   ...
]
```

In this new format, the input/output information is given by the parameter `io` inside the feature.

- `i` = input
- `o` = output
- `io` = input/output

Example of feature:

```
{
    "name": "myfeature",
    "io": "i"
    ...
}
```

==== InfluxDB

* Retention policy can now be configured in InfluxDB datasource settings.
* Add `create_database` to InfluxDB datasource settings for enabling/disabling database creation (default = `true`).

==== Miscellaneous

Multiprocessing optimizations.

Fix: Loud ML now serializes `null` instead of `nan` in the `mse` field of the prediction result.


=== Enteprise edition

* Added MongoDB connector.
* Added Warp10 connector.
