#!/bin/bash
#
# This script builds a release version of Loud ML (based on Debian Stretch
# packages) and deploys the image on DockerHub.
#
# Requirements:
#  - DockerHub password
#
# Environment variables:
#  - DOCKER_ID_USER: DockerHub login (defaults to 'loudml')

set -ex

: "${DOCKER_ID_USER:=loudml}"
export DOCKER_ID_USER

declare -r tag="loudml:latest"
declare -r dir="remote"

echo "deb http://loudml.s3-website-eu-west-1.amazonaws.com/repo/deb/ stretch main" \
    > "$dir/loudml-1.x.list"
docker build --no-cache -t "$tag" "$dir"
docker login --username "$DOCKER_ID_USER"
docker tag "$tag" "$DOCKER_ID_USER/$tag"
docker push "$DOCKER_ID_USER/$tag"
docker logout
