FROM tensorflow/tensorflow:1.13.2-gpu-py3

LABEL maintainer="packaging@loudml.io"
EXPOSE 8077

COPY --chown=_apt:root repo /repo
COPY loudml-1.x.list /etc/apt/sources.list.d/loudml-1.x.list

RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
               loudml loudml-base \
    && apt-get purge -y

RUN rm -rf /usr/lib/loudml/vendor/tensorflow

COPY loudml-gpu.yml /etc/loudml/config.yml
CMD /usr/bin/loudmld
