FROM debian:stretch-slim

LABEL maintainer="packaging@redmintnetwork.fr"
EXPOSE 8077

COPY repo /repo
COPY loudml-1.x.list /etc/apt/sources.list.d/loudml-1.x.list

RUN apt-get update \
    && apt-get install -y python3-pip \
    && apt-get install -y --allow-unauthenticated \
               loudml loudml-api loudml-base loudml-influx loudml-elastic \
    && apt-get purge -y

COPY loudml.yml /etc/loudml/config.yml
ENTRYPOINT /usr/bin/loudmld
