[[api-jobs]]
== Jobs API

The jobs API allows to get a typed JSON document from the current
jobs running asynchronously based on its identifier. The following example gets a
JSON document from the job with identifier `b67c10d6-3886-4285-a19c-2b908323238a`:

=== Getting job information

[source,js]
--------------------------------------------------
GET /jobs/<job_ids>
--------------------------------------------------

Use the semicolon separator to specify more than one identifier in the request url.

Example with two job identifiers:

[source,js]
--------------------------------------------------
GET /jobs/b67c10d6-3886-4285-a19c-2b908323238a;b67c10d6-3886-4285-a19c-2b908323238b
--------------------------------------------------

Example with one job identifier:

[source,js]
--------------------------------------------------
GET /jobs/b67c10d6-3886-4285-a19c-2b908323238a
--------------------------------------------------

The result of the above get operation is an array with information
for each job identifier present in the request url:

[source,js]
--------------------------------------------------
[{
  "id": "b67c10d6-3886-4285-a19c-2b908323238a", 
  "state": "done", 
  "result": null,
  "type": "training"
}]
--------------------------------------------------

The job `state` will have one of the following values:

[horizontal]
`waiting`::    Job is waiting to be scheduled
`running`::    Job is running and the result is not yet ready
`done`::       Job is completed and the result is available
`failed`::     Job failed. The error string will return more information
`canceled`::   Job was cancel by the user

The job `result` will contain the JSON output for the job, or null
if the job does not return any value.

A top level GET operation will list all jobs.

[source,js]
--------------------------------------------------
GET /jobs
--------------------------------------------------

=== Cancelling one or more jobs

[source,js]
--------------------------------------------------
POST /jobs/<job_ids>/_cancel
--------------------------------------------------

Use the semicolon separator to specify more than one identifier in the request url.

Example:

[source,js]
--------------------------------------------------
POST /jobs/b67c10d6-3886-4285-a19c-2b908323238a/_cancel
--------------------------------------------------
