#!/bin/sh 
# Intialize Bonsai module

# ---------------------------------------------------------------------------
# Configuration

# Elasticsearch REST API URL.
elastic="http://${ELASTICSEARCH_ADDR:-"localhost:9200"}"

# Elasticsearch template
template=/etc/bonsai/bonsai.template.json

# Wait for Elasticsearch to be ready
# Services dependencies is not sufficient. If one day there is a systemd
# unit named elasticsearch.socket, we should depend on that instead.
wait_for_es() {
    max_wait_es=20

    while ! netstat -ln|grep ":9200"; do
        sleep 1
        wait_es=$((wait_es + 1))
        if [ $wait_es -gt $max_wait_es ]; then
            echo "Unable to connect to Elasticsearch" 1>&2
            exit 1
        fi
    done
}

# es_put KEY VALUE
# Set KEY to VALUE on current Elasticsearch, using its REST API. VALUE
# follows curl syntax for --data argument.
es_put() {
    key="$1"
    val="$2"

    curl -XPUT "$elastic/$key" -d "$val"
}

# Install Elasticsearch template if not already present
configure_elasticsearch() {
    [[ "$elastic" == *"localhost"* ]] && wait_for_es

    cur="$(curl -XGET $elastic/_template/bonsai)"
#FIXME: template versioning
    if [ "$cur" = "{}" ]; then
        es_put _template/bonsai @$template
    fi
}

configure_elasticsearch

