#!/bin/sh

for deb in *.deb; do
    case "$deb" in
    loudml-base_*|loudml-import_*|loudml-api_*)
            continue
            ;;
    *)
        echo "Checking package $deb"
        if dpkg-deb -c "$deb" | grep "\.py$"; then
            echo "Source code found when expecting byte-code only."
            exit 1
        fi
        ;;
    esac
done
