---
datasources:
  - name: kapacitor
    type: influxdb
    addr: kapacitor:9092
    database: loudml
    retention_policy: autogen
    create_database: false
  - name: influx
    type: influxdb
    addr: influxdb:8086
    database: telegraf
    retention_policy: autogen

storage:
  path: /var/lib/loudml

server:
  listen: 0.0.0.0:8077
