[[setup]]
= Set up Loud ML

[partintro]
--
This section includes information on how to setup Loud ML and get it
running, including:

* Downloading
* Installing
* Starting
* Configuring

[[supported-platforms]]
[float]
== Supported platforms

The matrix of officially supported operating systems is:

.Supported Operating Systems
[options="header"]
|=======================
|Distribution|Version      
|Linux CentOS 7    | >= 7.3 
|Linux CentOS 8    | >= 8.0
|Fedora 30         |
|Fedora 31         |
|Linux Debian 9    | stretch
|Linux Ubuntu      | 18.04
|Docker            | -
|======================

Loud ML is tested on the listed platforms, but it may
work on other platforms too.

[float]
[[tf-version]]
== TensorFlow Version

Loud ML is built and tested with a TensorFlow version {tensorflow_version}. This dependency is pinned via the `requirements.txt` file in the source code.
 
The standard version provided by Google is embedded in the `loudml-base` package and is automatically installed in a vendor/ directory for DEB and RPM builds.

Using an unsupported TensorFlow version will cause issues. Contact us if you need another TensorFlow version.

--

include::setup/install.asciidoc[]

include::setup/configuration.asciidoc[]

include::setup/sysconfig.asciidoc[]

include::setup/stopping.asciidoc[]
