Document: loudml
Title: Debian loudml Manual
Author: <insert document author here>
Abstract: This manual describes what loudml is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/loudml/loudml.sgml.gz

Format: postscript
Files: /usr/share/doc/loudml/loudml.ps.gz

Format: text
Files: /usr/share/doc/loudml/loudml.text.gz

Format: HTML
Index: /usr/share/doc/loudml/html/index.html
Files: /usr/share/doc/loudml/html/*.html
