[[cli-forecast]]
== Forecast Command

The `forecast-model` command will return a forecast for the given time range,
and the given model. For example the command below will output data points
for model named `pricing-model` between now and the next 24 hours:

[source,bash]
--------------------------------------------------
loudml -e "forecast-model --from now --to now+1d pricing-model"
--------------------------------------------------

And this example will output result to `stdout`:

[source,js]
--------------------------------------------------
forecast(pricing-model): 100%|███████████████████████| 1/1 [00:01<00:00,  1.01s/it]
timestamp           @mean_value         loudml.mean_value  
1569574800.0        None                13286.228           
1569576000.0        None                12169.464           
1569577200.0        None                12049.305           
1569578400.0        None                10466.796
...
--------------------------------------------------

The `forecast-model` command supports the following options:

[horizontal]
`-f`::       (date) The `from` date in range query, supports <<date-math,Date Math>> notation.
`-t`::       (date) The `to` date in range query, supports <<date-math,Date Math>> notation. 
`-s`::       Will save output to the output bucket
`-i`::       Read data points from the specified input bucket
`-o`::       Write output data points to the specified output bucket
`-c`::       Stop forecasting if this constraint is met, ie when the target metric is either exceeded or becomes less than the specific constraint
`-p`::       Generate forecast confidence interval with +/- 100*p% range
`model_name`::      The model name


